chem:
  fp_option:
    type: morgan
    morgan_radius: 2
    morgan_n_bits: 256
  building_block_path: data/building_blocks/Enamine_Rush-Delivery_Building_Blocks-US_223244cmpd_20231001.sdf
  reaction_path: data/rxn_templates/comprehensive.txt
  rxn_matrix: data/processed/comp_256/matrix.pkl
  fpindex: data/processed/comp_256/fpindex.pkl

data:
  init_stack_weighted_ratio: 0.90

model:
  encoder_type: none
  encoder:
    d_model: 512
  decoder:
    d_model: 512
    nhead: 16
    dim_feedforward: 2048
    num_layers: 8
    pe_max_len: 32
    output_norm: false
    fingerprint_dim: ${chem.fp_option.morgan_n_bits}
    num_reaction_classes: 120
  fingerprint_head_type: diffusion_transformer
  fingerprint_head:
    d_model: 512
    fingerprint_dim: ${chem.fp_option.morgan_n_bits}
    diffusion_steps: 100
    diffusion_s: 0.01
    # Transformer should be larger for decoder-only setting
    n_bits_per_word: 16
    nhead: 16
    dim_feedforward: 2048
    num_layers: 6
    norm: false
    num_training_fingerprints_per_sample: 1
    enable_gradient_checkpointing: false

train:
  loss_weights:
    token: 1.0
    reaction: 1.0
    fingerprint_diffusion: 0.5
    fingerprint_bce: 0.0  # For monitoring purpose only
  val_loss_weights:
    token: 1.0
    reaction: 1.0
    fingerprint_diffusion: 0.0  # Multinomial diffusion loss does not drop
    fingerprint_bce: 0.5
  max_iters: 1_000_000
  val_freq: 5000
  max_grad_norm: 100.0
  optimizer:
    type: adamw
    lr: 1.e-4
    weight_decay: 0.01
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8
    patience: 10
    min_lr: 1.e-5
